@url = http://localhost:8000/api/people

POST {{url}}
Content-Type: application/json

{
  "first_name": "j",
  "last_name": "k"
}

###
PUT {{url}}/3
Content-Type: application/json

{
  "first_name": "j2",
  "last_name": "k2"
}

###
GET {{url}}

### GET one
GET {{url}}/3

### 
DELETE {{url}}/4