@base_url = http://localhost:5000/api 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJkMDAzIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYwMjg3NzUyfQ.72pytKeemTD-4wax_jkXAOKm8nNvwrjLjBCauflJWd0

GET {{base_url}}/all

###
GET {{base_url}}/greet
Authorization: Bearer {{token}}

###
GET {{base_url}}/admin
Authorization: Bearer {{token}}


### Login
POST {{base_url}}/login
Content-Type: application/json

{
    "username":"rd003",
    "password":"123"
}